Add additional warnings to eosio_exit annotations
EOSIO/eosio.cdt pull request #1030
Opened 2021-01-11 15:57 UTC by vzqzhang

2021-01-11 17:02 UTC, brianjohnson5972 requested changes

2021-01-11 17:02 UTC, brianjohnson5972 commented on libraries/eosiolib/contracts/eosio/system.hpp
> +    *  WARNING: this method immediately abort execution of wasm code that is on
@b1bart had indicated that he wanted extra emphasis on this, like using html markup.  Did you look into that?

2021-01-13 17:24 UTC, vzqzhang commented on libraries/eosiolib/contracts/eosio/system.hpp
> +    *  WARNING: this method immediately abort execution of wasm code that is on
Updated

2021-01-20 21:27 UTC, brianjohnson5972 approved these changes

2021-01-20 22:05 UTC, merged