break up name_tests into smaller tests, rename string_tests, remove s…
EOSIO/eosio.cdt pull request #1084
Opened 2021-04-08 18:57 UTC by praphael

…tatic

## Change Description

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-04-13 19:54 UTC, bogniq requested changes
Please check the comments about combining some tests when possible and some missing fix.

2021-04-13 22:25 UTC, praphael commented on tests/unit/name_tests.cpp
> +EOSIO_TEST_END
Agree, I will condense into single test.  My prporosal is 'name_type_test_ctr_str_lit' (constructor string literal).  I have had problems with test names being too long causes weird errors which is the reason for the abbrevation.

2021-04-13 22:25 UTC, praphael commented on tests/unit/name_tests.cpp
> +EOSIO_TEST_BEGIN(name_type_test_op_n_2)
Agree

2021-04-15 19:11 UTC, bogniq commented on tests/unit/name_tests.cpp
> +   static_assert(name{0ULL}.value == 0ULL);
One minor format issue: either use one space after bracket or not, so that the style is consistent within the whole file.

2021-04-15 20:37 UTC, bogniq approved these changes

2021-04-15 20:54 UTC, merged