disable copy constructor and copy assignment
EOSIO/eosio.cdt pull request #980
Opened 2020-10-16 20:54 UTC by allenhan2

Due to the way those types are initialized, it is not safe to allow the copy constructor or copy-assignment operator on the kv table type. 

## Change Description

- disable copy constructor and assignment
- default move constructor and assignment 

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2020-10-28 15:02 UTC, b1bart requested changes

2020-10-28 15:02 UTC, b1bart commented on libraries/eosiolib/contracts/eosio/key_value.hpp
> +   table(const table&) = delete;                         // disbale copy constructor
spelling error in disable

2020-10-28 15:02 UTC, b1bart commented on libraries/eosiolib/contracts/eosio/key_value.hpp
> +   table& operator=(const table&) = delete;              // disbale assginment copy operator
spelling error in assignment

2020-10-28 15:54 UTC, larryk85 reviewed
What is currently unsafe about it?

2020-10-28 15:56 UTC, tbfleming commented
It holds internal pointers to index members

2020-10-28 15:58 UTC, tbfleming commented
Which, BTW, is also incompatible with move. That should also be disabled.

2020-10-28 16:02 UTC, allenhan2 commented
> Which, BTW, is also incompatible with move. That should also be disabled.

Could you please elaborate a scenario for problem of move? thanks!

2020-10-28 16:15 UTC, tbfleming commented
Simplification of what's going on:

```
struct foo {
    int a = 0;
    int* p;

    foo(): p{&a} {}
};
```

2020-10-28 16:48 UTC, allenhan2 commented
It is a great example, but could it happen in the table class? disable move will make hard for utility functions.

2020-10-28 17:24 UTC, tbfleming commented
Like I said above, kv_table does this. It's part of how it keeps track of indexes.

2020-10-28 17:35 UTC, allenhan2 commented
okay, then, will disable the move.

2020-11-09 16:43 UTC, tbfleming approved these changes

2020-11-10 17:09 UTC, larryk85 approved these changes

2020-11-10 19:00 UTC, allenhan2 commented
no permission to merge, submitted tick for permission, https://blockone.freshservice.com/support/tickets/15178

2020-11-12 18:56 UTC, allenhan2 commented
@b1bart could you give another review, the merge is blocked by the request change, thanks,

2020-11-12 20:57 UTC, merged